# Generated by Django 3.1.7 on 2021-03-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=200)),
                ('position', models.IntegerField(blank=True, default=0, help_text='position')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
